### PR TITLE
Fix to work with Webpack 2

### PR DESCRIPTION
**Pull request by lucaskatayama**
Made modification to work with Webpack 2

### CODE REVIEW

**Comment by lucaskatayama** [comment]
Just update package.json webpack version...

**Comment by cerebrous** [comment]
For me this runs with Webpack 2.1.0-beta.22 but doesn't appear to actually set anything on `process.env`.

**Comment by fathert0rque** [comment]
For me this runs on webpack 2.1.0-beta.22 but doesn't actually set any keys on `process.env`

**Comment by lucaskatayama** [comment]
@chrisbarless If I use version **beta.22** I got a DefinePlugin deprecation 

```
webpack: Using compiler.parser is deprecated.
Use compiler.plugin("compilation", function(compilation, data) {
  data.normalModuleFactory.plugin("parser", function(parser, options) { parser.plugin(/* ... */); });
}); instead. It was called at applyDefine (/home/lucas/Dev/git/lucas/webpack-dotenv-plugin/node_modules/webpack/lib/DefinePlugin.js:65:20).
```

And a TypeError:

```
TypeError: compiler.parser.evaluate is not a function
    at Parser.<anonymous> (/home/lucas/Dev/git/lucas/webpack-dotenv-plugin/node_modules/webpack/lib/DefinePlugin.js:71:31)
    at Parser.applyPluginsBailResult (/home/lucas/Dev/git/lucas/travel-man/node_modules/tapable/lib/Tapable.js:52:27)
    at Parser.<anonymous> (/home/lucas/Dev/git/lucas/travel-man/node_modules/webpack/lib/Parser.js:249:24)
    at Parser.applyPluginsBailResult1 (/home/lucas/Dev/git/lucas/travel-man/node_modules/tapable/lib/Tapable.js:63:27)
    at Parser.evaluateExpression (/home/lucas/Dev/git/lucas/travel-man/node_modules/webpack/lib/Parser.js:941:21)
    at Parser.getRenameIdentifier (/home/lucas/Dev/git/lucas/travel-man/node_modules/webpack/lib/Parser.js:346:20)
    ....
```

If I use version **beta.25** It runs all good...

**Comment by nwinch** [comment]
Thanks @lucaskatayama.  I'm looking to move webpack as a peer dependency in #9 which will close this once that's merged.

**Comment by lucaskatayama** [comment]
Hum... That looks like a good way to solve this...

**Comment by nwinch** [comment]
This should now be solved with #13

**Pull request closed without merging**
